/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as CovenantRouteImport } from './routes/covenant'
import { Route as DappRouteImport } from './routes/dapp'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HubRouteRouteImport } from './routes/hub/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ViewersRouteImport } from './routes/viewers'
import { Route as HubIndexRouteImport } from './routes/hub/index'
import { Route as HubAuditRouteImport } from './routes/hub/audit'
import { Route as HubBillingRouteImport } from './routes/hub/billing'
import { Route as HubBrowserRouteImport } from './routes/hub/browser'
import { Route as HubCitizenRouteImport } from './routes/hub/citizen'
import { Route as HubClipsRouteImport } from './routes/hub/clips'
import { Route as HubCreateRouteImport } from './routes/hub/create'
import { Route as HubForumRouteImport } from './routes/hub/forum'
import { Route as HubFriendsRouteImport } from './routes/hub/friends'
import { Route as HubGatewayRouteImport } from './routes/hub/gateway'
import { Route as HubHoneypotRouteImport } from './routes/hub/honeypot'
import { Route as HubHydraRouteImport } from './routes/hub/hydra'
import { Route as HubLiveRouteImport } from './routes/hub/live'
import { Route as HubMarketRouteImport } from './routes/hub/market'
import { Route as HubMeshRouteImport } from './routes/hub/mesh'
import { Route as HubNeuronRouteImport } from './routes/hub/neuron'
import { Route as HubOsRouteImport } from './routes/hub/os'
import { Route as HubProfileRouteImport } from './routes/hub/profile'
import { Route as HubSettingsRouteImport } from './routes/hub/settings'
import { Route as HubShopRouteImport } from './routes/hub/shop'
import { Route as HubThemeRouteImport } from './routes/hub/theme'
import { Route as JournalIndexRouteImport } from './routes/journal/index'
import { Route as JournalSlugRouteImport } from './routes/journal/$slug'
import { Route as RHandleRouteImport } from './routes/r/$handle'
import { Route as VHandleRouteImport } from './routes/v/$handle'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiLureSplatRouteImport } from './routes/api/lure/$'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const CovenantRoute = CovenantRouteImport.update({
  id: '/covenant',
  path: '/covenant',
  getParentRoute: () => rootRouteImport,
} as any)
const DappRoute = DappRouteImport.update({
  id: '/dapp',
  path: '/dapp',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRouteRoute = HubRouteRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewersRoute = ViewersRouteImport.update({
  id: '/viewers',
  path: '/viewers',
  getParentRoute: () => rootRouteImport,
} as any)
const HubIndexRoute = HubIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HubRouteRoute,
} as any)
const HubAuditRoute = HubAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => HubRouteRoute,
} as any)
const HubBillingRoute = HubBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => HubRouteRoute,
} as any)
const HubBrowserRoute = HubBrowserRouteImport.update({
  id: '/browser',
  path: '/browser',
  getParentRoute: () => HubRouteRoute,
} as any)
const HubCitizenRoute = HubCitizenRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => HubRouteRoute,
} as any)
const HubClipsRoute = HubClipsRouteImport.update({
  id: '/clips',
  path: '/clips',
  getParentRoute: () => HubRouteRoute,
} as any)
const HubCreateRoute = HubCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => HubRouteRoute,
} as any)
const HubForumRoute = HubForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => HubRouteRoute,
} as any)
const HubFriendsRoute = HubFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => HubRouteRoute,
} as any)
const HubGatewayRoute = HubGatewayRouteImport.update({
  id: '/gateway',
  path: '/gateway',
  getParentRoute: () => HubRouteRoute,
} as any)
const HubHoneypotRoute = HubHoneypotRouteImport.update({
  id: '/honeypot',
  path: '/honeypot',
  getParentRoute: () => HubRouteRoute,
} as any)
const HubHydraRoute = HubHydraRouteImport.update({
  id: '/hydra',
  path: '/hydra',
  getParentRoute: () => HubRouteRoute,
} as any)
const HubLiveRoute = HubLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => HubRouteRoute,
} as any)
const HubMarketRoute = HubMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => HubRouteRoute,
} as any)
const HubMeshRoute = HubMeshRouteImport.update({
  id: '/mesh',
  path: '/mesh',
  getParentRoute: () => HubRouteRoute,
} as any)
const HubNeuronRoute = HubNeuronRouteImport.update({
  id: '/neuron',
  path: '/neuron',
  getParentRoute: () => HubRouteRoute,
} as any)
const HubOsRoute = HubOsRouteImport.update({
  id: '/os',
  path: '/os',
  getParentRoute: () => HubRouteRoute,
} as any)
const HubProfileRoute = HubProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => HubRouteRoute,
} as any)
const HubSettingsRoute = HubSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => HubRouteRoute,
} as any)
const HubShopRoute = HubShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => HubRouteRoute,
} as any)
const HubThemeRoute = HubThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => HubRouteRoute,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RHandleRoute = RHandleRouteImport.update({
  id: '/r/$handle',
  path: '/r/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const VHandleRoute = VHandleRouteImport.update({
  id: '/v/$handle',
  path: '/v/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLureSplatRoute = ApiLureSplatRouteImport.update({
  id: '/api/lure/$',
  path: '/api/lure/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hub': typeof HubRouteRouteWithChildren
  '/company': typeof CompanyRoute
  '/compliance': typeof ComplianceRoute
  '/covenant': typeof CovenantRoute
  '/dapp': typeof DappRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/viewers': typeof ViewersRoute
  '/hub/audit': typeof HubAuditRoute
  '/hub/billing': typeof HubBillingRoute
  '/hub/browser': typeof HubBrowserRoute
  '/hub/citizen': typeof HubCitizenRoute
  '/hub/clips': typeof HubClipsRoute
  '/hub/create': typeof HubCreateRoute
  '/hub/forum': typeof HubForumRoute
  '/hub/friends': typeof HubFriendsRoute
  '/hub/gateway': typeof HubGatewayRoute
  '/hub/honeypot': typeof HubHoneypotRoute
  '/hub/hydra': typeof HubHydraRoute
  '/hub/live': typeof HubLiveRoute
  '/hub/market': typeof HubMarketRoute
  '/hub/mesh': typeof HubMeshRoute
  '/hub/neuron': typeof HubNeuronRoute
  '/hub/os': typeof HubOsRoute
  '/hub/profile': typeof HubProfileRoute
  '/hub/settings': typeof HubSettingsRoute
  '/hub/shop': typeof HubShopRoute
  '/hub/theme': typeof HubThemeRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/r/$handle': typeof RHandleRoute
  '/v/$handle': typeof VHandleRoute
  '/hub/': typeof HubIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/lure/$': typeof ApiLureSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/compliance': typeof ComplianceRoute
  '/covenant': typeof CovenantRoute
  '/dapp': typeof DappRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/viewers': typeof ViewersRoute
  '/hub/audit': typeof HubAuditRoute
  '/hub/billing': typeof HubBillingRoute
  '/hub/browser': typeof HubBrowserRoute
  '/hub/citizen': typeof HubCitizenRoute
  '/hub/clips': typeof HubClipsRoute
  '/hub/create': typeof HubCreateRoute
  '/hub/forum': typeof HubForumRoute
  '/hub/friends': typeof HubFriendsRoute
  '/hub/gateway': typeof HubGatewayRoute
  '/hub/honeypot': typeof HubHoneypotRoute
  '/hub/hydra': typeof HubHydraRoute
  '/hub/live': typeof HubLiveRoute
  '/hub/market': typeof HubMarketRoute
  '/hub/mesh': typeof HubMeshRoute
  '/hub/neuron': typeof HubNeuronRoute
  '/hub/os': typeof HubOsRoute
  '/hub/profile': typeof HubProfileRoute
  '/hub/settings': typeof HubSettingsRoute
  '/hub/shop': typeof HubShopRoute
  '/hub/theme': typeof HubThemeRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/r/$handle': typeof RHandleRoute
  '/v/$handle': typeof VHandleRoute
  '/hub': typeof HubIndexRoute
  '/journal': typeof JournalIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/lure/$': typeof ApiLureSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hub': typeof HubRouteRouteWithChildren
  '/company': typeof CompanyRoute
  '/compliance': typeof ComplianceRoute
  '/covenant': typeof CovenantRoute
  '/dapp': typeof DappRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/viewers': typeof ViewersRoute
  '/hub/audit': typeof HubAuditRoute
  '/hub/billing': typeof HubBillingRoute
  '/hub/browser': typeof HubBrowserRoute
  '/hub/citizen': typeof HubCitizenRoute
  '/hub/clips': typeof HubClipsRoute
  '/hub/create': typeof HubCreateRoute
  '/hub/forum': typeof HubForumRoute
  '/hub/friends': typeof HubFriendsRoute
  '/hub/gateway': typeof HubGatewayRoute
  '/hub/honeypot': typeof HubHoneypotRoute
  '/hub/hydra': typeof HubHydraRoute
  '/hub/live': typeof HubLiveRoute
  '/hub/market': typeof HubMarketRoute
  '/hub/mesh': typeof HubMeshRoute
  '/hub/neuron': typeof HubNeuronRoute
  '/hub/os': typeof HubOsRoute
  '/hub/profile': typeof HubProfileRoute
  '/hub/settings': typeof HubSettingsRoute
  '/hub/shop': typeof HubShopRoute
  '/hub/theme': typeof HubThemeRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/r/$handle': typeof RHandleRoute
  '/v/$handle': typeof VHandleRoute
  '/hub/': typeof HubIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/lure/$': typeof ApiLureSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hub'
    | '/company'
    | '/compliance'
    | '/covenant'
    | '/dapp'
    | '/faq'
    | '/login'
    | '/pricing'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/viewers'
    | '/hub/audit'
    | '/hub/billing'
    | '/hub/browser'
    | '/hub/citizen'
    | '/hub/clips'
    | '/hub/create'
    | '/hub/forum'
    | '/hub/friends'
    | '/hub/gateway'
    | '/hub/honeypot'
    | '/hub/hydra'
    | '/hub/live'
    | '/hub/market'
    | '/hub/mesh'
    | '/hub/neuron'
    | '/hub/os'
    | '/hub/profile'
    | '/hub/settings'
    | '/hub/shop'
    | '/hub/theme'
    | '/journal/$slug'
    | '/r/$handle'
    | '/v/$handle'
    | '/hub/'
    | '/journal/'
    | '/api/auth/$'
    | '/api/lure/$'
    | '/api/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/company'
    | '/compliance'
    | '/covenant'
    | '/dapp'
    | '/faq'
    | '/login'
    | '/pricing'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/viewers'
    | '/hub/audit'
    | '/hub/billing'
    | '/hub/browser'
    | '/hub/citizen'
    | '/hub/clips'
    | '/hub/create'
    | '/hub/forum'
    | '/hub/friends'
    | '/hub/gateway'
    | '/hub/honeypot'
    | '/hub/hydra'
    | '/hub/live'
    | '/hub/market'
    | '/hub/mesh'
    | '/hub/neuron'
    | '/hub/os'
    | '/hub/profile'
    | '/hub/settings'
    | '/hub/shop'
    | '/hub/theme'
    | '/journal/$slug'
    | '/r/$handle'
    | '/v/$handle'
    | '/hub'
    | '/journal'
    | '/api/auth/$'
    | '/api/lure/$'
    | '/api/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/hub'
    | '/company'
    | '/compliance'
    | '/covenant'
    | '/dapp'
    | '/faq'
    | '/login'
    | '/pricing'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/viewers'
    | '/hub/audit'
    | '/hub/billing'
    | '/hub/browser'
    | '/hub/citizen'
    | '/hub/clips'
    | '/hub/create'
    | '/hub/forum'
    | '/hub/friends'
    | '/hub/gateway'
    | '/hub/honeypot'
    | '/hub/hydra'
    | '/hub/live'
    | '/hub/market'
    | '/hub/mesh'
    | '/hub/neuron'
    | '/hub/os'
    | '/hub/profile'
    | '/hub/settings'
    | '/hub/shop'
    | '/hub/theme'
    | '/journal/$slug'
    | '/r/$handle'
    | '/v/$handle'
    | '/hub/'
    | '/journal/'
    | '/api/auth/$'
    | '/api/lure/$'
    | '/api/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HubRouteRoute: typeof HubRouteRouteWithChildren
  CompanyRoute: typeof CompanyRoute
  ComplianceRoute: typeof ComplianceRoute
  CovenantRoute: typeof CovenantRoute
  DappRoute: typeof DappRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ViewersRoute: typeof ViewersRoute
  JournalSlugRoute: typeof JournalSlugRoute
  RHandleRoute: typeof RHandleRoute
  VHandleRoute: typeof VHandleRoute
  JournalIndexRoute: typeof JournalIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiLureSplatRoute: typeof ApiLureSplatRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/covenant': {
      id: '/covenant'
      path: '/covenant'
      fullPath: '/covenant'
      preLoaderRoute: typeof CovenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dapp': {
      id: '/dapp'
      path: '/dapp'
      fullPath: '/dapp'
      preLoaderRoute: typeof DappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub': {
      id: '/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof HubRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viewers': {
      id: '/viewers'
      path: '/viewers'
      fullPath: '/viewers'
      preLoaderRoute: typeof ViewersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/': {
      id: '/hub/'
      path: '/'
      fullPath: '/hub/'
      preLoaderRoute: typeof HubIndexRouteImport
      parentRoute: typeof HubRouteRoute
    }
    '/hub/audit': {
      id: '/hub/audit'
      path: '/audit'
      fullPath: '/hub/audit'
      preLoaderRoute: typeof HubAuditRouteImport
      parentRoute: typeof HubRouteRoute
    }
    '/hub/billing': {
      id: '/hub/billing'
      path: '/billing'
      fullPath: '/hub/billing'
      preLoaderRoute: typeof HubBillingRouteImport
      parentRoute: typeof HubRouteRoute
    }
    '/hub/browser': {
      id: '/hub/browser'
      path: '/browser'
      fullPath: '/hub/browser'
      preLoaderRoute: typeof HubBrowserRouteImport
      parentRoute: typeof HubRouteRoute
    }
    '/hub/citizen': {
      id: '/hub/citizen'
      path: '/citizen'
      fullPath: '/hub/citizen'
      preLoaderRoute: typeof HubCitizenRouteImport
      parentRoute: typeof HubRouteRoute
    }
    '/hub/clips': {
      id: '/hub/clips'
      path: '/clips'
      fullPath: '/hub/clips'
      preLoaderRoute: typeof HubClipsRouteImport
      parentRoute: typeof HubRouteRoute
    }
    '/hub/create': {
      id: '/hub/create'
      path: '/create'
      fullPath: '/hub/create'
      preLoaderRoute: typeof HubCreateRouteImport
      parentRoute: typeof HubRouteRoute
    }
    '/hub/forum': {
      id: '/hub/forum'
      path: '/forum'
      fullPath: '/hub/forum'
      preLoaderRoute: typeof HubForumRouteImport
      parentRoute: typeof HubRouteRoute
    }
    '/hub/friends': {
      id: '/hub/friends'
      path: '/friends'
      fullPath: '/hub/friends'
      preLoaderRoute: typeof HubFriendsRouteImport
      parentRoute: typeof HubRouteRoute
    }
    '/hub/gateway': {
      id: '/hub/gateway'
      path: '/gateway'
      fullPath: '/hub/gateway'
      preLoaderRoute: typeof HubGatewayRouteImport
      parentRoute: typeof HubRouteRoute
    }
    '/hub/honeypot': {
      id: '/hub/honeypot'
      path: '/honeypot'
      fullPath: '/hub/honeypot'
      preLoaderRoute: typeof HubHoneypotRouteImport
      parentRoute: typeof HubRouteRoute
    }
    '/hub/hydra': {
      id: '/hub/hydra'
      path: '/hydra'
      fullPath: '/hub/hydra'
      preLoaderRoute: typeof HubHydraRouteImport
      parentRoute: typeof HubRouteRoute
    }
    '/hub/live': {
      id: '/hub/live'
      path: '/live'
      fullPath: '/hub/live'
      preLoaderRoute: typeof HubLiveRouteImport
      parentRoute: typeof HubRouteRoute
    }
    '/hub/market': {
      id: '/hub/market'
      path: '/market'
      fullPath: '/hub/market'
      preLoaderRoute: typeof HubMarketRouteImport
      parentRoute: typeof HubRouteRoute
    }
    '/hub/mesh': {
      id: '/hub/mesh'
      path: '/mesh'
      fullPath: '/hub/mesh'
      preLoaderRoute: typeof HubMeshRouteImport
      parentRoute: typeof HubRouteRoute
    }
    '/hub/neuron': {
      id: '/hub/neuron'
      path: '/neuron'
      fullPath: '/hub/neuron'
      preLoaderRoute: typeof HubNeuronRouteImport
      parentRoute: typeof HubRouteRoute
    }
    '/hub/os': {
      id: '/hub/os'
      path: '/os'
      fullPath: '/hub/os'
      preLoaderRoute: typeof HubOsRouteImport
      parentRoute: typeof HubRouteRoute
    }
    '/hub/profile': {
      id: '/hub/profile'
      path: '/profile'
      fullPath: '/hub/profile'
      preLoaderRoute: typeof HubProfileRouteImport
      parentRoute: typeof HubRouteRoute
    }
    '/hub/settings': {
      id: '/hub/settings'
      path: '/settings'
      fullPath: '/hub/settings'
      preLoaderRoute: typeof HubSettingsRouteImport
      parentRoute: typeof HubRouteRoute
    }
    '/hub/shop': {
      id: '/hub/shop'
      path: '/shop'
      fullPath: '/hub/shop'
      preLoaderRoute: typeof HubShopRouteImport
      parentRoute: typeof HubRouteRoute
    }
    '/hub/theme': {
      id: '/hub/theme'
      path: '/theme'
      fullPath: '/hub/theme'
      preLoaderRoute: typeof HubThemeRouteImport
      parentRoute: typeof HubRouteRoute
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$handle': {
      id: '/r/$handle'
      path: '/r/$handle'
      fullPath: '/r/$handle'
      preLoaderRoute: typeof RHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$handle': {
      id: '/v/$handle'
      path: '/v/$handle'
      fullPath: '/v/$handle'
      preLoaderRoute: typeof VHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lure/$': {
      id: '/api/lure/$'
      path: '/api/lure/$'
      fullPath: '/api/lure/$'
      preLoaderRoute: typeof ApiLureSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HubRouteRouteChildren {
  HubAuditRoute: typeof HubAuditRoute
  HubBillingRoute: typeof HubBillingRoute
  HubBrowserRoute: typeof HubBrowserRoute
  HubCitizenRoute: typeof HubCitizenRoute
  HubClipsRoute: typeof HubClipsRoute
  HubCreateRoute: typeof HubCreateRoute
  HubForumRoute: typeof HubForumRoute
  HubFriendsRoute: typeof HubFriendsRoute
  HubGatewayRoute: typeof HubGatewayRoute
  HubHoneypotRoute: typeof HubHoneypotRoute
  HubHydraRoute: typeof HubHydraRoute
  HubLiveRoute: typeof HubLiveRoute
  HubMarketRoute: typeof HubMarketRoute
  HubMeshRoute: typeof HubMeshRoute
  HubNeuronRoute: typeof HubNeuronRoute
  HubOsRoute: typeof HubOsRoute
  HubProfileRoute: typeof HubProfileRoute
  HubSettingsRoute: typeof HubSettingsRoute
  HubShopRoute: typeof HubShopRoute
  HubThemeRoute: typeof HubThemeRoute
  HubIndexRoute: typeof HubIndexRoute
}

const HubRouteRouteChildren: HubRouteRouteChildren = {
  HubAuditRoute: HubAuditRoute,
  HubBillingRoute: HubBillingRoute,
  HubBrowserRoute: HubBrowserRoute,
  HubCitizenRoute: HubCitizenRoute,
  HubClipsRoute: HubClipsRoute,
  HubCreateRoute: HubCreateRoute,
  HubForumRoute: HubForumRoute,
  HubFriendsRoute: HubFriendsRoute,
  HubGatewayRoute: HubGatewayRoute,
  HubHoneypotRoute: HubHoneypotRoute,
  HubHydraRoute: HubHydraRoute,
  HubLiveRoute: HubLiveRoute,
  HubMarketRoute: HubMarketRoute,
  HubMeshRoute: HubMeshRoute,
  HubNeuronRoute: HubNeuronRoute,
  HubOsRoute: HubOsRoute,
  HubProfileRoute: HubProfileRoute,
  HubSettingsRoute: HubSettingsRoute,
  HubShopRoute: HubShopRoute,
  HubThemeRoute: HubThemeRoute,
  HubIndexRoute: HubIndexRoute,
}

const HubRouteRouteWithChildren = HubRouteRoute._addFileChildren(
  HubRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HubRouteRoute: HubRouteRouteWithChildren,
  CompanyRoute: CompanyRoute,
  ComplianceRoute: ComplianceRoute,
  CovenantRoute: CovenantRoute,
  DappRoute: DappRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ViewersRoute: ViewersRoute,
  JournalSlugRoute: JournalSlugRoute,
  RHandleRoute: RHandleRoute,
  VHandleRoute: VHandleRoute,
  JournalIndexRoute: JournalIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiLureSplatRoute: ApiLureSplatRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
