name: Sentinel Daemon CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable
      - name: Build Sentinel Daemon
        run: cargo build --manifest-path sentinel-daemon/Cargo.toml --verbose
      - name: Run Tests
        run: cargo test --manifest-path sentinel-daemon/Cargo.toml --verbose
